# For more information: https://laravel.com/docs/sail
version: '3'
services:
      mipsoja-webservice:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}

        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
      postgres:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
#            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ROOT_HOST: "%"
#            MYSQL_DATABASE: '172.20.0.3/api${DB_DATABASE}'
#            MYSQL_USER: '${DB_USERNAME}'
#            MYSQL_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-postgres:/var/lib/postgres'
            - './vendor/laravel/sail/database/postgres/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
          test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_DATABASE}" ]
          retries: 3
          timeout: 5s
      pgadmin:
        image: 'dpage/pgadmin4'
        environment:
          PGADMIN_DEFAULT_EMAIL: 'pgadmin@pgadmin.org'
          PGADMIN_DEFAULT_PASSWORD: 'pgadmin'
        ports:
          - '5050:80'
        depends_on:
          - postgres
networks:
    sail:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
